### ISSUE TITLE
Qiskit -> Qiskit-Forest -> QVM TypeError: can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by jwoehr** [quantastica/qiskit-forest#1] opened 2019-12-23 16:56 UTC
Issue Description
-----------------
Attempt to run Qiskit job against qvm, e.g.,  `Forest_qasm_simulator`, hangs with mulitprocessing error ... the output follows a call `qiskit.job.monitor.job_monitor()`
```
Job Status: job is actively runningTraceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects
```

How to Reproduce
----------------
Forest support is being added to a Qiskit-based tool. It may be sufficient to insert here the job dictionary from the job as passed to Qiskit 

```
{   '_as_qvm': True,
    '_backend': <ForestBackend('Forest_qasm_simulator') from None()>,
    '_future': <Future at 0x7f7bb6b08048 state=running>,
    '_job_id': 'e20bb464-78a5-47ba-9f27-2bfcfe75fc7d',
    '_lattice_name': 'qasm_simulator',
    '_qobj': QasmQobj(config=QasmQobjConfig(max_credits=3, memory=False, memory_slots=3, n_qubits=3, parameter_binds=[], shots=1024), experiments=[QasmQobjExperiment(config=QasmQobjExperimentConfig(memory_slots=3, n_qubits=3), header=QobjExperimentHeader(clbit_labels=[['c', 0], ['c', 1], ['c', 2]], creg_sizes=[['c', 3]], memory_slots=3, n_qubits=3, name='circuit0', qreg_sizes=[['q', 3]], qubit_labels=[['q', 0], ['q', 1], ['q', 2]]), instructions=[QasmQobjInstruction(name='h', qubits=[0]), QasmQobjInstruction(name='h', qubits=[1]), QasmQobjInstruction(name='h', qubits=[2]), QasmQobjInstruction(memory=[0], name='measure', qubits=[0]), QasmQobjInstruction(memory=[1], name='measure', qubits=[1]), QasmQobjInstruction(memory=[2], name='measure', qubits=[2])])], header=QobjHeader(backend_name='Forest', backend_version='0.0.1'), qobj_id='20aa036c-ef61-472c-a26d-9e740f26d2eb', schema_version='1.1.0', type='QASM'),
    '_result': None}
```
### Error Output

```
^CProcess Process-4:
Process Process-1:
Process Process-7:
Process Process-8:
Process Process-6:
Process Process-3:
Process Process-5:
Process Process-2:
Traceback (most recent call last):
  File "/home/jax/work/QISKit/qis_job/qasm_job.py", line 176, in <module>
    QJ.do_it()
  File "/home/jax/work/QISKit/qis_job/qis_job.py", line 170, in do_it
    self.one_exp(f_path)
  File "/home/jax/work/QISKit/qis_job/qis_job.py", line 397, in one_exp
    job_monitor(job_exp)
  File "/home/jax/work/QISKit/DEV/qiskit-terra/qiskit/tools/monitor/job_monitor.py", line 86, in job_monitor
    quiet=quiet, output=output)
  File "/home/jax/work/QISKit/DEV/qiskit-terra/qiskit/tools/monitor/job_monitor.py", line 42, in _text_checker
    time.sleep(interval)
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
KeyboardInterrupt
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
KeyboardInterrupt
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
```

Environment Context
-------------------

Operating System: Ubuntu 18.04

Forest Linux SDK: 2.15.1 updated today

Python Version (`python -V`): Python 3.6.9

Qiskit Forest: quantastica-qiskit-forest-0.9.8

Quilc Version (`quilc --version`): 1.15.1 [5e8966d]

QVM Version (`qvm --version`): 1.15.1 [feb7fe6]

Python Environment Details (`pip freeze` or `conda list`):

```
alabaster==0.7.12
alembic==0.9.3.dev0
anaconda==0.0.1.1
antlr4-python3-runtime==4.7.2
appdirs==1.4.3
apturl==0.5.2
argh==0.26.2
asn1crypto==0.24.0
astroid==2.3.3
atomicwrites==1.3.0
attrs==19.3.0
autopep8==1.4.4
Babel==2.7.0
backcall==0.1.0
beautifulsoup4==4.6.0
bleach==3.1.0
blinker==1.4
Brlapi==0.6.6
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
click==6.7
cloudpickle==1.2.2
colorama==0.3.7
command-not-found==0.3
coreapi==2.3.3
coreschema==0.0.4
coverage==4.5.4
cplex==12.9.0.0
cryptography==2.8
cupshelpers==1.0
cvxopt==1.2.3
cycler==0.10.0
Cython==0.29.13
ddt==1.2.1
decorator==4.4.1
defer==1.0.6
defusedxml==0.6.0
diff-match-patch==20181111
dill==0.3.1.1
discover==0.4.0
distro-info===0.18ubuntu0.18.04.1
dlx==1.0.4
docloud==1.0.375
docplex==2.10.155
docutils==0.15.2
dulwich==0.19.13
entrypoints==0.3
fastdtw==0.3.2
feedparser==5.2.1
filelock==3.0.12
flake8==3.7.9
Flask==0.12.2
Flask-BabelEx==0.9.3
Flask-Compress==1.4.0
Flask-Gravatar==0.4.2
Flask-HTMLmin==1.3.2
Flask-Login==0.4.0
Flask-Mail==0.9.1
Flask-Migrate==2.1.1
Flask-Paranoid==0.2.0
Flask-Principal==0.4.0
Flask-Security==1.7.5
Flask-SQLAlchemy==2.1
Flask-WTF==0.14.2
future==0.18.2
h5py==2.10.0
helpdev==0.6.10
html5lib==0.999999999
htmlmin==0.1.12
httplib2==0.9.2
hypothesis==4.41.3
idna==2.8
imagesize==1.1.0
immutables==0.6
importlib-metadata==1.2.0
inflection==0.3.1
intervaltree==3.0.2
ipykernel==5.1.3
ipython==7.10.1
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
itsdangerous==0.24
itypes==1.1.0
jedi==0.14.1
jeepney==0.4.1
Jinja2==2.10.3
joblib==0.14.0
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.0.0
jupyter-core==4.6.1
keyring==19.3.0
keyrings.alt==3.0
kiwisolver==1.1.0
language-selector==0.1
launchpadlib==1.10.6
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
lazy-object-proxy==1.4.3
louis==3.5.0
lxml==4.2.1
macaroonbakery==1.1.3
Mako==1.0.7
MarkupSafe==1.1.1
marshmallow==3.2.1
marshmallow-polyfield==5.7
matplotlib==3.1.1
mccabe==0.6.1
mistune==0.8.4
more-itertools==8.0.2
mpmath==1.1.0
msgpack==0.6.2
nbconvert==5.6.1
nbformat==4.4.0
nbimporter==0.3.1
ndg-httpsclient==0.5.1
nest-asyncio==1.0.0
netifaces==0.10.4
networkx==2.4
nlopt==2.6.1
nose==1.3.7
notebook==6.0.1
ntlm-auth==1.4.0
numpy==1.17.3
numpydoc==0.9.1
nxpd==0.2.0
oauth==1.0.1
oauthlib==2.0.6
olefile==0.45.1
packaging==19.2
pandas==0.25.1
pandocfilters==1.4.2
parameterized==0.7.0
paramiko==2.0.0
parso==0.5.1
passlib==1.7.1
pathtools==0.1.2
pbr==5.4.3
pexpect==4.7.0
pickleshare==0.7.5
Pillow==5.1.0
pkg-resources==0.0.0
pkginfo==1.5.0.1
pluggy==0.13.1
ply==3.11
prometheus-client==0.7.1
prompt-toolkit==3.0.2
protobuf==3.0.0
psutil==5.6.7
psycopg2==2.8.4
ptyprocess==0.6.0
py==1.8.0
pyasn1==0.4.2
pybind11==2.4.2
pycairo==1.16.2
pycodestyle==2.5.0
pycparser==2.19
pycrypto==2.6.1
pycups==1.9.73
pydocstyle==4.0.1
pydot==1.4.1
pyenchant==2.0.0
pyflakes==2.1.1
Pygments==2.5.2
pygobject==3.26.1
pyinotify==0.9.6
PyJWT==1.5.3
pylatexenc==2.1
pylint==2.4.4
pylintfileheader==0.0.2
pymacaroons==0.13.0
Pympler==0.8
PyNaCl==1.1.2
pyodbc==4.0.26
pyopencl==2019.1.1
pyOpenSSL==17.5.0
pyparsing==2.4.5
PyQt5==5.12.3
PyQt5-sip==12.7.0
PyQtWebEngine==5.12.1
-e git+https://github.com/rpmuller/pyquante2.git@6e34cb4480ae7dbd8c5e44d221d8b27584890c83#egg=pyquante2
-e git+https://github.com/rigetti/pyquil.git@a708040e405eb79f5b07c62c9b5ef33067a71023#egg=pyquil
pyRFC3339==1.0
pyrsistent==0.15.6
pyscf==1.6.4
pytest==5.2.0
python-apt==1.6.4
python-dateutil==2.8.1
python-debian==0.1.32
python-jsonrpc-server==0.3.2
python-language-server==0.31.2
python-rapidjson==0.9.1
pytools==2019.1.1
pytz==2019.3
pyxdg==0.26
PyYAML==5.2
pyzmq==18.1.1
qcgpu==0.1.1
QDarkStyle==2.7
-e git+git@github.com:/jwoehr/qiskit.git@a4d045ec1709c20ab04de58ebd41d1b682939875#egg=qiskit
-e git+git@github.com:/jwoehr/qiskit-aer.git@9932431faa4ae3afe286f56bab3f24787089b96c#egg=qiskit_aer
-e git+git@github.com:/jwoehr/qiskit-aqua.git@40942fd6a4af8c7dbe64eb5f411a2b686685b768#egg=qiskit_aqua
-e git+git@github.com:/jwoehr/qiskit-aqua-interfaces.git@d062c77822f88594b73de3b0c83b9cb9374d1799#egg=qiskit_aqua_interfaces
-e git+git@github.com:jwoehr/qiskit-ibmq-provider.git@7c288cec8a09b38523547c25bb30796f7daad69b#egg=qiskit_ibmq_provider
-e git+git@github.com:/jwoehr/qiskit-ignis.git@6587084a08a2e364225b6e2472ebaeeae98712a6#egg=qiskit_ignis
-e git+git@github.com:/jwoehr/qiskit-community-qcgpu-provider@46f66e521776898ce01797ff8d6a79ca5c73d01f#egg=qiskit_qcgpu_provider
-e git+git@github.com:/jwoehr/qiskit-terra.git@75420eaca6d6b14d49ebfdad126467f274ef20d7#egg=qiskit_terra
qrcode==6.1
QtAwesome==0.6.0
qtconsole==4.6.0
QtPy==1.9.0
Quandl==3.4.8
quantastica-qconvert==0.9.7
-e git+https://github.com/quantastica/qiskit-forest.git@d30673786cfbe46faf5184cc59d4234083830534#egg=quantastica_qiskit_forest
-e git+git@github.com:/jwoehr/quantuminspire@c4614b8e80a7b8a2b1b297456be47a6ecec5c5a2#egg=quantuminspire
readme-renderer==24.0
reno==2.11.3
reportlab==3.4.0
requests==2.22.0
requests-ntlm==1.1.0
requests-toolbelt==0.9.1
requests-unixsocket==0.1.5
rope==0.14.0
rpcq==3.0.0
ruamel.yaml==0.16.5
ruamel.yaml.clib==0.2.0
scikit-build==0.10.0
scikit-learn==0.21.3
scipy==1.3.1
screen-resolution-extra==0.0.0
seaborn==0.9.0
SecretStorage==3.1.1
Send2Trash==1.5.0
simplejson==3.13.2
six==1.13.0
sklearn==0.0
snowballstemmer==2.0.0
sortedcontainers==2.1.0
Sphinx==2.2.2
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-websupport==1.1.0
spyder==4.0.0
spyder-kernels==1.8.1
SQLAlchemy==1.1.11
sqlparse==0.2.4
ssh-import-id==5.7
sshtunnel==0.1.4
sympy==1.4
system-service==0.3
systemd-python==234
terminado==0.8.2
testpath==0.4.4
toml==0.10.0
torch==1.3.0
tornado==6.0.3
tox==3.14.0
tqdm==4.31.1
traitlets==4.3.3
twine==1.13.0
typed-ast==1.4.0
ubuntu-drivers-common==0.0.0
ufw==0.36
ujson==1.35
unattended-upgrades==0.1
unity-scope-calculator==0.1
unity-scope-chromiumbookmarks==0.1
unity-scope-colourlovers==0.1
unity-scope-devhelp==0.1
unity-scope-firefoxbookmarks==0.1
unity-scope-manpages==0.1
unity-scope-openclipart==0.1
unity-scope-texdoc==0.1
unity-scope-tomboy==0.1
unity-scope-virtualbox==0.1
unity-scope-yelp==0.1
unity-scope-zotero==0.1
uritemplate==3.0.0
urllib3==1.25.7
usb-creator==0.3.3
virtualenv==16.7.7
wadllib==1.3.2
watchdog==0.9.0
wcwidth==0.1.7
webencodings==0.5.1
websockets==7.0
Werkzeug==0.16.0
widgetsnbextension==3.5.1
wrapt==1.11.2
WTForms==2.1
wurlitzer==2.0.0
xkit==0.0.0
yapf==0.29.0
zipp==0.6.0
zope.interface==4.3.2
```

**Comment by perak** [comment] 2019-12-23 17:55
@jwoehr thanks for reporting. Expect answer/fix in next few hours.

**Comment by perak** [comment] 2019-12-23 21:09
@jwoehr I cannot reproduce your issue. 

- Can you please provide original Qiskit code?

- Do you have the same issue with any experiment using ForestBackend, or only with this one?

**Comment by jwoehr** [comment] 2019-12-23 21:22
It's part of a tool I wrote and use daily: my GitHub project [qis_job](https://github.com/jwoehr/qis_job) in the master branch. `qis_job` already supports IBMQ and QuantumInspire; I've been trying to add Forest support.

Say I have everything installed (qiskit, forest, pyquil, etc.) and set up with `qvm` and `qilc` running as services and a file `foo.qasm` in the same directory as a clone of the `qis_job` project. Then:

`python qasm_job.py  --qvm -b qasm_simulator foo.qasm`

should run `foo.qasm` against the qvm qasm simulator.

Alternatively, I can try to write a simpler example!

**Comment by perak** [comment] 2019-12-23 21:29
@jwoehr this line in your code: https://github.com/jwoehr/qis_job/blob/master/qis_job.py#L232

You are using `as_qvm=True` which is valid only when backend name is one of Rigetti QPU Lattices. For normal execution on QVM set `as_qvm` to `False`.

Option `as_qvm` instructs QVM to mimic QPU given as backend name (wiring scheme, noise etc.)

**Comment by perak** [comment] 2019-12-23 21:31
One more thing: please update `quantastica-qconvert` to latest version `0.9.9` (somehow we didn't set minimal version in qiskit-forest/setup.py - fixing that now).

**Comment by jwoehr** [comment] 2019-12-23 21:34
Made the change and upgraded `quantastica-qconvert` with same outcome.

**Comment by perak** [comment] 2019-12-23 21:35
Just a second to clone qis_job and to try the same...

**Comment by jwoehr** [comment] 2019-12-23 21:36
I didn't check it in yet .

**Comment by jwoehr** [comment] 2019-12-23 21:37
Now it's there with the new flag.

**Comment by perak** [comment] 2019-12-23 21:38
In meantime, can you please try to run your example directly (without qiskit, qis_job, ForestBackend etc.) :

```
from pyquil import Program, get_qc
from pyquil.gates import H, MEASURE
import numpy as np

p = Program()

ro = p.declare('ro', memory_type='BIT', memory_size=3)

p.inst(H(0))
p.inst(H(1))
p.inst(H(2))
p.inst(MEASURE(0, ro[0]))
p.inst(MEASURE(1, ro[1]))
p.inst(MEASURE(2, ro[2]))

p.wrap_in_numshots_loop(1024)

qc = get_qc('3q-qvm')
print(qc.run(p))
```

just run the file

**Comment by jwoehr** [comment] 2019-12-23 21:39
That runs correctly.

**Comment by jwoehr** [comment] 2019-12-23 21:40
```
 python cant_pickle.py 
[[0 0 0]
 [1 1 1]
 [0 0 1]
 ...
 [1 1 1]
 [1 1 0]
 [0 1 1]]
```

**Comment by perak** [comment] 2019-12-23 21:47
Somehow qis_job doesn't work for me (when executed from the root of the cloned repository) `ModuleNotFoundError: No module named 'qiskit.providers.ibmq.job.exceptions'` but I have `qiskit-ibmq-provider` installed... but let's not debug it here.

Let me give you one more program to try:

**Comment by jwoehr** [comment] 2019-12-23 21:49
I'm always coding against the master branch so maybe I'm calling something that has changed namespaces since the last release level.

**Comment by perak** [comment] 2019-12-23 21:53
Please try following:

```
from pyquil import Program, get_qc
from pyquil.gates import *

p = Program('PRAGMA INITIAL_REWIRING "PARTIAL"')

ro = p.declare('ro', memory_type='BIT', memory_size=3)

p += H(0)
p += H(1)
p += H(2)
p += MEASURE(0, ro[0])
p += MEASURE(1, ro[1])
p += MEASURE(2, ro[2])
p.wrap_in_numshots_loop(1024)

qc = get_qc('3q-qvm')

print(qc.run(p))
```

**Comment by jwoehr** [comment] 2019-12-23 22:11
Runs.
```
$ python cant_pickle1.py 
[[1 1 0]
 [1 1 1]
 [0 0 1]
 ...
 [1 0 1]
 [0 1 0]
 [0 1 1]]
```
I must be doing something really stupid in my code :)

**Comment by perak** [comment] 2019-12-23 22:19
Maybe it's not you - maybe it's me :)

I just published fresh code, please update `quantastica-qiskit-forest` to latest - to be in sync (and please try running your code again)

And help me run `qis_job`: I will make issue for `ModuleNotFoundError: No module named 'qiskit.providers.ibmq.job.exceptions'` in your repo now

**Comment by perak** [comment] 2019-12-23 22:29
@jwoehr qis_job works after upgrading qiskit to latest. I'm trying to reproduce your issue...

**Comment by perak** [comment] 2019-12-23 22:30
How to tell qis_job that I want to use QVM?

**Comment by jwoehr** [comment] 2019-12-23 22:30
I updated `qiskit-forest` with same result.

Perhaps I will have to make a much simpler code body and work my way up to modifying qis_job.

**Comment by perak** [comment] 2019-12-23 22:32
Ah, got it `--qvm`...

**Comment by jwoehr** [comment] 2019-12-23 22:32
> How to tell qis_job that I want to use QVM?

To run `foo.qasm` you enter:
`python qasm_job --qvm -b qasm_simulator foo.qasm`

**Comment by perak** [comment] 2019-12-23 22:33
`python qasm_job.py --qvm -b qasm_simulator ./qasm_examples/yiqing_simple.qasm` works without issues:

```
Job Status: job has successfully run
Forest_qasm_simulator 2019-12-23T23:32:22.535332
000;001;010;011;100;101;110;111;
127;134;117;122;125;133;135;131;
```

**Comment by jwoehr** [comment] 2019-12-23 22:36
whoo!

I guess something wrong with my setup of the Forest stuff or something.

**Comment by perak** [comment] 2019-12-23 22:36
Where is your QVM running? In a docker, or on bare metal?

**Comment by perak** [comment] 2019-12-23 22:36
And how did you start it? (which arguments you use with `qvm`) ?

**Comment by jwoehr** [comment] 2019-12-23 22:37
bare metal. I just start it like Pyquil says
```
./quilc -S&
./qvm -S -c &
```

**Comment by perak** [comment] 2019-12-23 22:38
OK, please try to limit number of workers to 1 (there are some multi-processing related messages in errors...)

Try something like:

```
qvm -S -c -w 1
```

**Comment by jwoehr** [comment] 2019-12-23 22:41
> ```
> qvm -S -c -w 1
> ```

Same error.

**Comment by jwoehr** [comment] 2019-12-23 22:42
Wonder if perhaps it is a Python 3.6 problem?!

**Comment by perak** [comment] 2019-12-23 22:42
But... it works when you directly execute pyQuil code, so multiprocessing is not the issue...

Hum.... could be python.

**Comment by jwoehr** [comment] 2019-12-23 22:43
Thanks for your help. You have proven that the code works. I will play with my setup. I have other machines.  I will post back here and let you know.

**Comment by perak** [comment] 2019-12-23 22:44
(qasm_job is nice tool btw 👍 )

**Comment by perak** [comment] 2019-12-23 22:45
OK, please keep me updated. Thank you!

**Comment by jwoehr** [comment] 2019-12-23 22:51
> (qasm_job is nice tool btw +1 )

Thank you ... I'll be looking at the code tomorrow .. have to run some holiday errands now!

Thanks again for being available interactively when so many people are off on vacation :)

**Comment by jwoehr** [comment] 2019-12-23 22:52
PS I'm waiting for authorization from Rigetti for real QPU access to support that in qasm_job.

**Comment by jwoehr** [comment] 2019-12-24 05:18
Hmm, got different and more informative error on my Python 3.7 machine ... first it says `Job Status: job is actively running` then status changes as captured below: 
```
$ qjob --qvm -b qasm_simulator qasm_examples/yiqing_simple.qasm
Job Status: job incurred error     
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jwoehr/work/Qiskit/qis_job/qasm_job.py", line 176, in <module>
    QJ.do_it()
  File "/home/jwoehr/work/Qiskit/qis_job/qis_job.py", line 170, in do_it
    self.one_exp(f_path)
  File "/home/jwoehr/work/Qiskit/qis_job/qis_job.py", line 398, in one_exp
    result_exp = job_exp.result()
  File "/home/jwoehr/work/Qiskit/qiskit-forest/quantastica/qiskit_forest/ForestJob.py", line 71, in result
    self.wait(timeout)
  File "/home/jwoehr/work/Qiskit/qiskit-forest/quantastica/qiskit_forest/ForestJob.py", line 68, in wait
    raise self._future.exception()
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects
```

**Comment by jwoehr** [comment] 2019-12-24 06:11
BTW ... I did cleanup of [QisJob](https://github.com/jwoehr/qis_job) and pushed a new release tonight [v2.8](https://github.com/jwoehr/qis_job/releases/tag/v2.8)

I've gotten rid of the `qasm_job.py` script and the `__main__` now is in `qis_job.py`. Works just like it did before, but now there's only one script instead of two.

**Comment by mirko796** [comment] 2019-12-26 12:56
Confirmed, definitely breaks on Linux.

Will be fixed ASAP

**Comment by perak** [comment] 2019-12-27 12:48
@jwoehr fixed by @mirko796 

please `pip install --upgrade quantastica-qiskit-forest` to latest `0.9.13`

**Comment by jwoehr** [comment] 2019-12-27 13:22
Works for me, thanks!

**Closed as completed** 2019-12-27 13:23 UTC

**Comment by perak** [comment] 2019-12-27 13:31
You're welcome 👍
